storm-nimbus:
  command: --daemon nimbus drpc
  image: clescot/rancher-storm:6
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
storm-supervisor:
  command: --daemon supervisor logviewer
  image: clescot/rancher-storm:6
  ports:
    - "8000:8000"
    - "6700:6700"
    - "6701:6701"
    - "6702:6702"
    - "6703:6703"
storm-ui:
  command: --daemon ui
  image: clescot/rancher-storm:6
  ports:
    - "8080:8080"
