storm-nimbus:
  command: --daemon nimbus drpc
  image: clescot/rancher-storm:68
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  external_links:
    - zookeeper/zookeeper:zk

storm-supervisor:
  command: --daemon supervisor logviewer
  image: clescot/rancher-storm:68
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  ports:
    - "8000:8000"
    - "6700:6700"
    - "6701:6701"
    - "6702:6702"
    - "6703:6703"
  links:
    - storm-nimbus:nimbus
  external_links:
    - zookeeper/zookeeper:zk
    - kafka/kafka:kafka
  depends_on:
    - storm-nimbus

storm-ui:
  command: --daemon ui
  image: clescot/rancher-storm:68
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  ports:
    - "8080:8080"
  links:
    - storm-nimbus:nimbus
  external_links:
    - zookeeper/zookeeper:zk
  depends_on:
    - storm-nimbus
    - storm-supervisor
